# Dati Strutturati

I **dati strutturati** sono informazioni organizzate in un formato predefinito e rigido, tipicamente una tabella composta da righe (osservazioni) e colonne (variabili o feature).
Ogni colonna ha un tipo di dato ben definito (es. intero, testo, data). In Python, la libreria principale per manipolare dati strutturati è **Pandas**, che mette a disposizione l'oggetto `DataFrame`.

In [1]:
import pandas as pd

In [15]:
BASE_URL = "https://github.com/ProfAI/machine-learning-fondamenti/blob/main/datasets/"

### CSV

Il formato **CSV (Comma-Separated Values)** è uno dei formati più semplici e diffusi per lo scambio di dati tabulari. Ogni riga del file rappresenta una riga della tabella, e i valori delle colonne sono separati da una virgola `,`.
- **Vantaggi**: Leggero, leggibile come testo semplice, supportato universalmente.
- **Svantaggi**: Non supporta tipi di dati complessi o formule, non ha uno standard rigoroso per la gestione di caratteri speciali (es. virgole nel testo).

In [12]:
df = pd.read_csv(BASE_URL+"shirts_example.csv", index_col=0)
df.head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99

### TSV

Il formato **TSV (Tab-Separated Values)** è del tutto analogo al CSV, ma utilizza una tabulazione (`\t`) come separatore anziché una virgola.
- **Perché usarlo**: È particolarmente utile quando i dati di testo all'interno delle colonne contengono già virgole, evitando errori di parsing senza ricorrere a complessi sistemi di virgolette.

In [13]:
df = pd.read_csv(BASE_URL+"shirts_example.tsv", index_col=0, sep="\t")
df.head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99

### EXCEL
Formati supportati xls, xlsx, xlsm, xlsb, odf, ods e odt.

I file **Excel** (come `.xlsx` o il formato open source `.ods` usato in questo esempio) sono formati binari più complessi rispetto ai file di testo come CSV/TSV. Possono contenere più fogli di lavoro, formattazioni, formule e grafici.
- **In Pandas**: Per leggere questi file usiamo `pd.read_excel`. Spesso è necessario installare motori di terze parti (come `odfpy` per `.ods` o `openpyxl` per `.xlsx`) per consentire a Pandas di decodificare il file binario.

In [15]:
pip install odfpy

Collecting odfpy
  Downloading odfpy-1.4.1.tar.gz (717 kB)
Requirement already satisfied: defusedxml in c:\users\gfgul\anaconda3\lib\site-packages (from odfpy) (0.7.1)
Building wheels for collected packages: odfpy
  Building wheel for odfpy (setup.py): started
  Building wheel for odfpy (setup.py): finished with status 'done'
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=137339 sha256=f65d5a958697eaf0972f589d7653a331655afc6eec693662568a618e384c371e
  Stored in directory: c:\users\gfgul\appdata\local\pip\cache\wheels\ea\af\da\2bdd7308f7b334429a558df1e36d31864cd19c07ede92ddf0e
Successfully built odfpy
Installing collected packages: odfpy
Successfully installed odfpy-1.4.1
Note: you may need to restart the kernel to use updated packages.

In [6]:
df = pd.read_excel(BASE_URL+"shirts_example.ods", index_col=0)
df.head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99

#### HTML

Le pagine **HTML** contengono tabelle definite dal tag `<table>`. Pandas permette di effettuare uno scraping automatico di queste tabelle tramite la funzione `pd.read_html`, che analizza il codice HTML e restituisce una lista di DataFrame corrispondenti a tutte le tabelle trovate nella pagina.

In [12]:
df = pd.read_html(BASE_URL+"shirts_example.html", index_col=0, header=0)
df[0].head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99

### XML

**XML (Extensible Markup Language)** è un linguaggio di marcatura gerarchico che utilizza tag personalizzati per definire la struttura dei dati. È molto comune per lo scambio di informazioni sul web.
- **In Pandas**: A partire dalla versione 1.3.0, Pandas ha introdotto la comoda funzione `pd.read_xml` per convertire direttamente strutture XML nidificate in tabelle bidimensionali.

In [17]:
# serve la version 1.3.0
!pip install pandas --upgrade # --user # solo per l'utente corrente

Requirement already satisfied: pandas in c:\users\gfgul\anaconda3\lib\site-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in c:\users\gfgul\anaconda3\lib\site-packages (from pandas) (1.20.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\gfgul\anaconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\gfgul\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\gfgul\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [14]:
df = pd.read_xml(BASE_URL+"shirts_example.xml")
df.head()

   id taglia  colore  prezzo
0   0      S  bianco    4.99
1   1      M  bianco   19.99
2   2     XL  bianco   12.49
3   3     XL  bianco   14.99
4   4      S  bianco   14.99

### JSON

**JSON (JavaScript Object Notation)** è il formato standard per le API web e lo scambio di dati asincrono. È strutturato come coppie chiave-valore (molto simile ai dizionari Python) e supporta strutture annidate.
- **In Pandas**: La funzione `pd.read_json` permette di caricare file JSON. Se la struttura è piatta, la conversione in DataFrame è immediata; per strutture complesse e nidificate si può usare `pd.json_normalize`.

In [13]:
df = pd.read_json(BASE_URL+"shirts_example.json")
df.head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99